### PR TITLE
turn back on unit tests

### PR DESCRIPTION
**Pull request by gavinsimpson**
This uncomments all bar one unit test. Running this shows lots of failures that we need to track down.

### CODE REVIEW

**Comment by gavinsimpson** [comment]
(This is failing as expected given that we're now testing more of the package in the unit tests...)

**Comment by SimonGoring** [comment]
One of the variable names in the API has changed names somehow, the API documentation lists `CollUnitType` as one of the variables returned by the `dataset` command, but it's coming through as `CollType` now.  This seems to be causing almost all of the failures.

**Comment by SimonGoring** [comment]
Ha, really bad timing, somethings going on with the whole API. . . Even the documented examples online aren't working.

**Comment by gavinsimpson** [comment]
Phew!

**Comment by SimonGoring** [comment]
Yeah, I couldn't figure it out, and then went to the most basic level, and lo and behold. . .

**Comment by gavinsimpson** [comment]
They must have been doing stuff as I was running my checks because (I think) all the examples ran without error it was just the stuff in `test_neotoma()`...

**Comment by SimonGoring** [comment]
Yes, that's what I think happened.  I was thinking it might be useful to
actually pass some of the API examples directly so that we can test whether
or not it's the API or the functions.

**Comment by SimonGoring** [comment]
Yeah, it's all bonkers.  I added one line to `get_dataset` (see commit 96c31fd4a8135304bdcda12f70445f41e82ee0b2) and that should fix everything (plus the API side fixes that have just happened.

Try running the tests now, they should all work.

**Pull request merged**
